version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: admin-database
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: wy930208
      MYSQL_DATABASE: mamibus
      MYSQL_USER: wy
      MYSQL_PASSWORD: wy930208
      TZ: Asia/Shanghai
    networks:
      - backend
    expose:
      - "3306"
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: admin-redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6378:6379"
    networks:
      - backend
    environment:
      TZ: Asia/Shanghai

  admin-server:
    build: ./Xmw_server
    container_name: admin-server
    # restart: always
    ports:
      - "3000:6688"
    networks:
      - backend
    depends_on:
      - mysql
      - redis

networks:
  backend:
    driver: bridge
